{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{default attribute_base='ContentObjectAttribute'
         html_class='full'}
{if $attribute.content.has_stored_card}

<div class="element">
<label>Current stored card</label>
XXXX-XXXX-XXXX-{$attribute.content.number|extract_right( 4 )|wash( xhtml )}<br />
expires {$attribute.content.month}/{$attribute.content.year}
</div>
<input class="button" type="submit" name="CustomActionButton[{$attribute.id}_delete_creditcard]" value="{'Remove creditcard'|i18n( 'design/standard/content/datatype' )}" />


{else}

<label>Card type</label>
<select name="{$attribute_base}_ezcreditcard_type_{$attribute.id}" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" >
{def $types = hash('1','MasterCard','2','Visa','3','Discover','4','American Express')}
{foreach $types as $type => $name}
<option value="{$type}">{$name}</option>
{/foreach}
</select>
<label>Name on card:</label>
<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ezcreditcard_name_{$attribute.id}" value="{$attribute.content.name|wash( xhtml )}" />
<label>Creditcard number</label>
<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ezcreditcard_number_{$attribute.id}" value="{$attribute.content.number|wash( xhtml )}" />
<label>Security Code</label>
<input maxlength="4" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ezcreditcard_securitycode_{$attribute.id}" value="{$attribute.content.securitycode|wash( xhtml )}" />

<div class="block">
    <div class="element">
    <label>Month</label>
    <select name="{$attribute_base}_ezcreditcard_month_{$attribute.id}" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" >
    {def $months = array('01','02','03','04','05','06','07','08','09','10','11','12')}
    {foreach $months as $month}
    <option value="{$month}" {if $month|eq($attribute.content.month)}selected{/if}>{$month}</option>
    {/foreach}
    </select>
    </div>
    
    <div class="element">
    <label>Year</label>
    <select name="{$attribute_base}_ezcreditcard_year_{$attribute.id}" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" >
    {def $year=currentdate()|datetime(custom,'%Y')}
    {for $year to sum($year,10) as $i}
    <option value="{$i}" {if $i|eq($attribute.content.year)}selected{/if}>{$i}</option>
    {/for}
    </select>
    </div>
    <div class="break"></div>
</div>


{/if}

{/default}

