{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="block">

    <div class="element">
        <label>{'Quantity'|i18n('content/datatype/edit/xrowbillingcycle')}</label>
        <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_quantity" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_billingcycle_quantity_{$attribute.id}">
            {for 0 to 100 as $i}
                <option value="{$i}"{if $i|eq($attribute.content.quantity)} selected="selected"{/if}>{$i}</option>
            {/for}
        </select>

    </div>

    <div class="element">
        <label>{'Period'|i18n('content/datatype/edit/xrowbillingcycle')}</label>
        <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_data_int" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_billingcycle_period_{$attribute.id}">
            {for 0 to 5 as $i}
                <option value="{$i}"{if $i|eq($attribute.content.period)} selected="selected"{/if}>{$attribute.content.text_array[$i]}</option>
            {/for}
        </select>
    </div>

    <div class="break"></div>

</div>
